version: '3'
services:
  api:
    image: longhuo/message-service:latest
    ports:
      - "80:3000"
    deploy:
      mode: replicated
      replicas: 2
    env_file:
      - .env
    command: [ "npm", "run", "start:container" ]
