version: '3.9'
services:
  api:
    image: longhuo/message-service:latest
    networks:
      - backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file:
      - .env.dev
    command: [ "npm", "run", "test:integrated" ]
  mongo:
    image: mongo:latest
    networks:
      - backend
    #volumes: one time database should not persist

networks:
  backend:
    driver: bridge
