version: '3'
services:
  api:
    image: longhuo/message-service:latest
    networks:
      - backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file:
      - .env.dev
    environment:
      - NODE_ENV=test
    command: [ "npm", "run", "test:integrated" ]

  mongo:
    image: mongo:latest
    logging:
      driver: none
    networks:
      - backend
    #volumes: one time database should not persist

networks:
  backend:
    driver: bridge
